"use client";

import { useState } from "react";

const money = (v) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(v || 0));
const meses = ["Janeiro 2026","Fevereiro 2026","Março 2026","Abril 2026","Maio 2026","Junho 2026"];
const dadosBase = {"Março 2026": { entradas: 6894.07, saidas: 7104.04, saldoContas: 115.13, cards: { fixas: { valor: 2430.22, itens: 7 }, dividas: { valor: 1984.55, itens: 4 }, cartoes: { valor: 1587.10, itens: 3 }, variaveis: { valor: 1102.17, itens: 12 }, receitas: { valor: 6894.07, itens: 5 }}}};
const cartoesIniciais = [
  { id: 1, nome: "Nubank", limite: 8800, usado: 3280, fechamento: 25, vencimento: 1, compras: [
    { id: 11, descricao: "Notebook Dell", data: "12/03/2026", total: 2400, parcelas: "8 de 12", categoria: "Tecnologia" },
    { id: 12, descricao: "Mercado", data: "18/03/2026", total: 480, parcelas: "à vista", categoria: "Alimentação" },
    { id: 13, descricao: "Passagem", data: "20/03/2026", total: 400, parcelas: "2 de 4", categoria: "Transporte" },
  ]},
  { id: 2, nome: "Itaú Azul", limite: 3500, usado: 920, fechamento: 5, vencimento: 12, compras: [
    { id: 21, descricao: "Farmácia", data: "08/03/2026", total: 220, parcelas: "à vista", categoria: "Saúde" },
    { id: 22, descricao: "Curso online", data: "14/03/2026", total: 700, parcelas: "3 de 6", categoria: "Educação" },
  ]},
];

function shellStyle(){return {minHeight:"100vh",background:"radial-gradient(circle at top, #18285d 0%, #09122e 38%, #050a19 100%)",color:"#F2F5FF",padding:"20px 16px 28px",fontFamily:'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'}}
function cardBase(extra={}){return {background:"rgba(12,19,44,.72)",border:"1px solid rgba(120,146,255,.14)",borderRadius:20,padding:"16px 16px 14px",boxShadow:"0 8px 22px rgba(0,0,0,.16)",...extra}}
function input(compact=false){return {width:"100%",background:"rgba(9,14,33,.92)",color:"#F3F6FF",border:"1px solid rgba(122,146,255,.18)",borderRadius:12,padding:compact?"10px 12px":"12px 14px",fontSize:15,outline:"none",boxSizing:"border-box"}}
function getDados(mes){return dadosBase[mes]||{entradas:0,saidas:0,saldoContas:0,cards:{fixas:{valor:0,itens:0},dividas:{valor:0,itens:0},cartoes:{valor:0,itens:0},variaveis:{valor:0,itens:0},receitas:{valor:0,itens:0}}}}

function SummaryCard({title,value,highlight}){return <div style={cardBase({minHeight:86,padding:"14px 16px 12px",background:highlight?"rgba(124,92,255,.16)":"rgba(12,19,44,.78)",border:highlight?"1px solid rgba(124,92,255,.35)":"1px solid rgba(120,146,255,.14)"})}><div style={{color:"rgba(222,228,255,.78)",fontSize:14,marginBottom:8}}>{title}</div><div style={{fontSize:24,fontWeight:800}}>{value}</div></div>}
function HomeMini({mes,setMes}){const dados=getDados(mes); const saldoMes=dados.entradas-dados.saidas; return <><section style={{...cardBase({borderRadius:24,padding:"16px 18px 14px",display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap"})}}><div><div style={{display:"inline-flex",padding:"8px 14px",borderRadius:999,background:"rgba(91,126,255,.18)",fontWeight:700,fontSize:14,marginBottom:10}}>Controle Financeiro • V3.7.2</div><div style={{fontSize:26,fontWeight:800}}>Olá, Thiago</div><div style={{marginTop:4,color:"rgba(212,220,255,.72)",fontSize:15}}>Cartões com acabamento mais refinado.</div></div><button style={{background:"transparent",color:"rgba(232,236,255,.85)",border:"1px solid rgba(130,148,255,.18)",borderRadius:14,padding:"10px 16px",fontWeight:700,fontSize:14,cursor:"pointer"}}>Sair</button></section><section style={{marginTop:14}}><div style={{color:"rgba(224,230,255,.8)",fontSize:14,marginBottom:8}}>Mês principal</div><select value={mes} onChange={(e)=>setMes(e.target.value)} style={{...input(),minWidth:220}}>{meses.map(m=><option key={m}>{m}</option>)}</select></section><section style={{marginTop:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><SummaryCard title="Saldo do mês" value={money(saldoMes)} highlight/><SummaryCard title="Entradas" value={money(dados.entradas)}/><SummaryCard title="Saídas" value={money(dados.saidas)}/><SummaryCard title="Saldo em contas" value={money(dados.saldoContas)}/></section></>}

function Placeholder({title,subtitle}){return <section style={cardBase({borderRadius:24,marginTop:16,padding:20})}><div style={{fontSize:24,fontWeight:800,marginBottom:8}}>{title}</div><div style={{color:"rgba(212,220,255,.72)",fontSize:15}}>{subtitle}</div></section>}
function StatChip({label,value}){return <div style={cardBase({minHeight:80,padding:"12px 14px 10px",boxShadow:"none"})}><div style={{fontSize:13,color:"rgba(212,220,255,.72)",marginBottom:6}}>{label}</div><div style={{fontSize:22,fontWeight:800}}>{value}</div></div>}
function CardItem({cartao,ativo,onClick}){const disponivel=cartao.limite-cartao.usado; return <button onClick={onClick} style={{...cardBase({padding:14,width:"100%",textAlign:"left",cursor:"pointer",boxShadow:ativo?"0 0 0 1px rgba(124,92,255,.28), 0 10px 24px rgba(76,61,174,.16)":"0 8px 22px rgba(0,0,0,.16)",background:ativo?"linear-gradient(180deg, rgba(124,92,255,.15), rgba(12,19,44,.88))":"rgba(12,19,44,.72)",borderColor:ativo?"rgba(124,92,255,.35)":"rgba(120,146,255,.14)"})}}><div style={{fontSize:18,fontWeight:800,marginBottom:6}}>{cartao.nome}</div><div style={{color:"rgba(220,228,255,.82)",fontSize:14}}>Fatura: {money(cartao.usado)}</div><div style={{color:"rgba(200,208,245,.72)",fontSize:13,marginTop:4,lineHeight:1.4}}>Disponível: {money(disponivel)} • Fecha {cartao.fechamento} • Vence {cartao.vencimento}</div></button>}
function CompraLinha({compra}){return <div style={{padding:"12px 0",borderBottom:"1px solid rgba(120,146,255,.10)",display:"grid",gridTemplateColumns:"1.2fr .6fr .45fr .45fr",gap:12,alignItems:"center"}}><div><div style={{fontWeight:700,fontSize:16}}>{compra.descricao}</div><div style={{color:"rgba(200,208,245,.72)",fontSize:13,marginTop:4}}>{compra.data} • {compra.categoria}</div></div><div style={{fontWeight:700}}>{money(compra.total)}</div><div style={{color:"rgba(220,228,255,.82)",fontSize:14}}>{compra.parcelas}</div><button style={{background:"rgba(255,255,255,.04)",color:"#F5F7FF",border:"1px solid rgba(128,150,255,.16)",borderRadius:10,padding:"8px 10px",fontWeight:700,cursor:"pointer",fontSize:14}}>Antecipar</button></div>}

function CartoesTab(){
  const [cartoes,setCartoes]=useState(cartoesIniciais); const [cartaoAtivoId,setCartaoAtivoId]=useState(cartoesIniciais[0].id); const [busca,setBusca]=useState(""); const [editando,setEditando]=useState(false); const [msg,setMsg]=useState("");
  const cartaoAtivo=cartoes.find(c=>c.id===cartaoAtivoId)||cartoes[0];
  const [limiteEdit,setLimiteEdit]=useState(cartaoAtivo.limite); const [fechamentoEdit,setFechamentoEdit]=useState(cartaoAtivo.fechamento); const [vencimentoEdit,setVencimentoEdit]=useState(cartaoAtivo.vencimento);
  const totalLimite=cartoes.reduce((s,c)=>s+c.limite,0); const totalUsado=cartoes.reduce((s,c)=>s+c.usado,0); const totalDisponivel=totalLimite-totalUsado; const comprasFiltradas=cartaoAtivo.compras.filter(c=>c.descricao.toLowerCase().includes(busca.toLowerCase()));
  function iniciarEdicao(){setLimiteEdit(cartaoAtivo.limite);setFechamentoEdit(cartaoAtivo.fechamento);setVencimentoEdit(cartaoAtivo.vencimento);setEditando(true);setMsg("")}
  function salvarEdicao(){setCartoes(prev=>prev.map(c=>c.id===cartaoAtivo.id?{...c,limite:Number(limiteEdit),fechamento:Number(fechamentoEdit),vencimento:Number(vencimentoEdit)}:c)); setEditando(false); setMsg("Cartão atualizado com sucesso.")}
  return <>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><SummaryCard title="Fatura do mês" value={money(totalUsado)}/><SummaryCard title="Limite total" value={money(totalLimite)}/><SummaryCard title="Disponível" value={money(totalDisponivel)} highlight/></section>
    <section style={{marginTop:14,display:"flex",gap:10,flexWrap:"wrap"}}><button style={{background:"linear-gradient(90deg,#6d7cff 0%, #8862ff 100%)",color:"#fff",border:"none",borderRadius:12,padding:"10px 14px",fontWeight:800,fontSize:14,cursor:"pointer"}}>Novo cartão</button><button style={{background:"rgba(255,255,255,.04)",color:"#fff",border:"1px solid rgba(128,150,255,.16)",borderRadius:12,padding:"10px 14px",fontWeight:800,fontSize:14,cursor:"pointer"}}>Nova compra</button></section>
    <section style={{marginTop:14,display:"grid",gridTemplateColumns:"280px 1fr",gap:14}}>
      <div style={cardBase({padding:14})}><div style={{fontSize:20,fontWeight:800,marginBottom:10}}>Meus cartões</div><div style={{display:"grid",gap:10}}>{cartoes.map(cartao=><CardItem key={cartao.id} cartao={cartao} ativo={cartaoAtivoId===cartao.id} onClick={()=>{setCartaoAtivoId(cartao.id);setEditando(false);setMsg("")}} />)}</div></div>
      <div style={cardBase({padding:18})}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:16,flexWrap:"wrap"}}>
          <div><div style={{fontSize:30,fontWeight:800}}>{cartaoAtivo.nome}</div><div style={{color:"rgba(212,220,255,.72)",fontSize:15,marginTop:6}}>Fecha dia {cartaoAtivo.fechamento} • Vence dia {cartaoAtivo.vencimento}</div></div>
          <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}>
            {!editando ? <button onClick={iniciarEdicao} style={{background:"rgba(255,255,255,.04)",color:"#fff",border:"1px solid rgba(128,150,255,.16)",borderRadius:12,padding:"10px 14px",fontWeight:700,cursor:"pointer",fontSize:14}}>Editar cartão</button> : <><button onClick={salvarEdicao} style={{background:"linear-gradient(90deg,#6d7cff 0%, #8862ff 100%)",color:"#fff",border:"none",borderRadius:12,padding:"10px 14px",fontWeight:700,cursor:"pointer",fontSize:14}}>Salvar</button><button onClick={()=>setEditando(false)} style={{background:"rgba(255,255,255,.04)",color:"#fff",border:"1px solid rgba(128,150,255,.16)",borderRadius:12,padding:"10px 14px",fontWeight:700,cursor:"pointer",fontSize:14}}>Cancelar</button></>}
          </div>
        </div>
        {msg ? <div style={{marginTop:12,padding:"10px 12px",borderRadius:12,background:"rgba(124,92,255,.14)",border:"1px solid rgba(124,92,255,.24)",color:"#E7DDFF",fontSize:14,fontWeight:600}}>{msg}</div> : null}
        <div style={{marginTop:16,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>
          <div style={cardBase({minHeight:82,padding:"12px 14px 10px",boxShadow:"none"})}><div style={{fontSize:13,color:"rgba(212,220,255,.72)",marginBottom:6}}>Limite total</div>{!editando?<div style={{fontSize:22,fontWeight:800}}>{money(cartaoAtivo.limite)}</div>:<input style={input(true)} value={limiteEdit} onChange={(e)=>setLimiteEdit(e.target.value)} />}</div>
          <div style={cardBase({minHeight:82,padding:"12px 14px 10px",boxShadow:"none"})}><div style={{fontSize:13,color:"rgba(212,220,255,.72)",marginBottom:6}}>Fechamento</div>{!editando?<div style={{fontSize:22,fontWeight:800}}>{cartaoAtivo.fechamento}</div>:<input style={input(true)} value={fechamentoEdit} onChange={(e)=>setFechamentoEdit(e.target.value)} />}</div>
          <div style={cardBase({minHeight:82,padding:"12px 14px 10px",boxShadow:"none"})}><div style={{fontSize:13,color:"rgba(212,220,255,.72)",marginBottom:6}}>Vencimento</div>{!editando?<div style={{fontSize:22,fontWeight:800}}>{cartaoAtivo.vencimento}</div>:<input style={input(true)} value={vencimentoEdit} onChange={(e)=>setVencimentoEdit(e.target.value)} />}</div>
        </div>
        <div style={{marginTop:18,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{fontSize:20,fontWeight:800}}>Compras</div><input placeholder="Buscar compra" value={busca} onChange={(e)=>setBusca(e.target.value)} style={{...input(true),minWidth:200,maxWidth:240}} /></div>
        <div style={{marginTop:8,display:"grid",gap:2}}>{comprasFiltradas.map(compra=><CompraLinha key={compra.id} compra={compra} />)}</div>
      </div>
    </section>
  </>}

export default function Page(){
  const [mes,setMes]=useState("Março 2026"); const [tab,setTab]=useState("cartoes");
  const itemStyle={flex:1,textAlign:"center",color:"rgba(231,236,255,.9)",fontWeight:700,fontSize:16,padding:"12px 8px",borderRadius:16,cursor:"pointer",userSelect:"none"};
  return <main style={shellStyle()}><div style={{maxWidth:1180,margin:"0 auto"}}>{tab==="inicio"&&<HomeMini mes={mes} setMes={setMes} />}{tab==="contas"&&<Placeholder title="Contas" subtitle="Aqui entra a listagem e edição das contas bancárias." />}{tab==="lancar"&&<Placeholder title="Lançar" subtitle="Aqui entra o formulário de receitas, despesas e pagamentos." />}{tab==="cartoes"&&<CartoesTab />}{tab==="mais"&&<Placeholder title="Mais" subtitle="Aqui entram categorias, filtros avançados e outras opções." />}<div style={{position:"sticky",bottom:16,marginTop:24,background:"rgba(8,14,34,.92)",border:"1px solid rgba(122,147,255,.16)",borderRadius:24,padding:10,display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8,backdropFilter:"blur(14px)",boxShadow:"0 16px 34px rgba(0,0,0,.28)"}}><div style={{...itemStyle,background:tab==="inicio"?"rgba(124,92,255,.16)":"transparent"}} onClick={()=>setTab("inicio")}>Início</div><div style={{...itemStyle,background:tab==="contas"?"rgba(124,92,255,.16)":"transparent"}} onClick={()=>setTab("contas")}>Contas</div><div style={{...itemStyle,background:tab==="lancar"?"rgba(124,92,255,.16)":"transparent"}} onClick={()=>setTab("lancar")}>Lançar</div><div style={{...itemStyle,background:tab==="cartoes"?"rgba(124,92,255,.16)":"transparent"}} onClick={()=>setTab("cartoes")}>Cartões</div><div style={{...itemStyle,background:tab==="mais"?"rgba(124,92,255,.16)":"transparent"}} onClick={()=>setTab("mais")}>Mais</div></div></div></main>}
